config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'chapters#index'
  resources :chapters do
    resources :sections
  end

  resources :sections do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  validates :name, :presence => true
  validates(:name, uniqueness: { case_sensitive: false })
  before_save(:upcase_first_letter)

  define_method(:upcase_first_letter) do
    self.name =  self.name.slice(0,1).capitalize + self.name.slice(1..-1)
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  validates :name, :presence => true
  validates(:name, uniqueness: { case_sensitive: false })
  before_save(:upcase_first_letter)

  define_method(:upcase_first_letter) do
    self.name =  self.name.slice(0,1).capitalize + self.name.slice(1..-1)
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter
  validates :name, :presence => true
  validates(:name, uniqueness: { case_sensitive: false })
  before_save(:upcase_first_letter)

  define_method(:upcase_first_letter) do
    self.name =  self.name.slice(0,1).capitalize + self.name.slice(1..-1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to chapters_path
    else
      render :new
    end
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])
    if @chapter.update(chapter_params)
      redirect_to chapters_path
    else
      render :edit
    end
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy
    redirect_to chapters_path
  end

  private
  def chapter_params
    params.require(:chapter).permit(:name)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  def new
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      redirect_to section_path(@lesson.section)
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  def update
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to section_path(@lesson.section)
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to section_path(@lesson.section)
  end

  private
  def lesson_params
    params.require(:lesson).permit(:name, :category, :day, :number, :text)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
  end

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.new
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.new(section_params)
    if @section.save
      redirect_to chapter_path(@section.chapter)
    else
      render :new
    end
  end

  def edit
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to chapter_path(@section.chapter)
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to chapter_path(@section.chapter)
  end


  private
  def section_params
    params.require(:section).permit(:name, :week)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/_form.html.erb
<%= render "layouts/errors", :object => @chapter %>

<%= form_for @chapter do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/chapters/edit.html.erb
<h1>Edit: <%= @chapter.name %></h1>

<%= render "form" %>

app/views/chapters/index.html.erb
<h1>Courses</h1>
<% @chapters.each do |chapter| %>
<p><%= link_to chapter.name, chapter_path(chapter) %></p>
<% end %>

<%= link_to "Create New Course", new_chapter_path %>

app/views/chapters/new.html.erb
<h1>Create New Course</h1>

<%= render "form" %>

app/views/chapters/show.html.erb
<h1><%= @chapter.name %></h1>

<% if @chapter.sections.any? %>

    <% @chapter.sections.each do |section| %>
      <p>
        (<%= section.week %>)
        <%= link_to section.name, chapter_section_path(@chapter, section) %>
      </p>
    <% end %>
<% else %>
  <p>There are no sections yet!</p>
<% end %>

<br>
<%= link_to "Add a Section", new_chapter_section_path(@chapter)%>
<br>

<%= link_to "Edit this Chapter", edit_chapter_path(@chapter) %>
<br>
<%= link_to "Delete this Chapter", chapter_path(@chapter),
                      :data => { :confirm => "Are you sure you want to delete this chapter/course?",
                      :method => "delete"} %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lhtp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= form_for [@section, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :day %>
  <%= f.text_field :day %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>

<%= render "form" %>

app/views/lessons/new.html.erb
<h1>Add a New Lesson</h1>

<%= render "form" %>

app/views/lessons/show.html.erb
<h4><%= @lesson.category %> <%= @lesson.day %></h4>

<h1><%= @lesson.name %></h1>

<p>
  <%= @lesson.text %>
</p>

<%= link_to "Edit lesson", edit_section_lesson_path(@section, @lesson) %>
<%= link_to "Delete lesson", section_lesson_path(@section, @lesson),
                         :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %>

app/views/sections/_form.html.erb
<%= render "layouts/errors", :object => @section %>

<%= form_for [@chapter, @section] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :week %>
  <%= f.text_field :week %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<h1>Edit Section</h1>

<%= render "form" %>

app/views/sections/new.html.erb
<h1>Create New Section</h1>

<%= render "form" %>

app/views/sections/show.html.erb
<h1><%= @section.name %></h1>

<% if @section.lessons.any? %>


    <% @section.lessons.each do |lesson| %>
      <p>
        <%= lesson.day %> <%= link_to lesson.name, section_lesson_path(@section, lesson) %>
      </p>
    <% end %>
<% else %>
  <p>There are no lessons yet!</p>
<% end %>

<%= link_to "Add a Lesson", new_section_lesson_path(@section)%>

<%= link_to "Edit section", edit_chapter_section_path(@section) %>
<%= link_to "Delete section", chapter_section_path(@section),
                         :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %>

<%= link_to "All Sections", chapter_path(@section.chapter) %>